{
    'name': 'Employee Requests',
    'version': '16.0.0.1',
    'author': 'Ahmed Amen',
    'license': 'AGPL-3',
    'category': 'Hr',
    'depends': [
        'base',
        'hr',
        'hr_payroll',
        'hr_contract',
        'emp_payslip',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/employee.xml',
        'views/liquidation.xml',
        'views/leave_request.xml',
        'views/salary_request.xml',
        'views/housing_allowance.xml',
        'views/overtime_request.xml',
        'views/end_service.xml',
        'views/res_config_settings.xml',
        'wizard/employee_wizard_view.xml',
        'views/menus.xml',
        'data/sequence.xml',
        'report/liquidation.xml',
    ],
    'installable': True,
    'application': True,
}
